/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventDetailsDataEventTournament model module.
 * @module model/GetEventDetailsDataEventTournament
 * @version 1.0.0
 */
export class GetEventDetailsDataEventTournament {
  /**
   * Constructs a new <code>GetEventDetailsDataEventTournament</code>.
   * @alias module:model/GetEventDetailsDataEventTournament
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventTournament</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventTournament} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventTournament} The populated <code>GetEventDetailsDataEventTournament</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventTournament();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetEventDetailsDataEventTournament.prototype.id = undefined;

