/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventMatchGames} from './GetEventDetailsDataEventMatchGames';
import {GetEventDetailsDataEventMatchStrategy} from './GetEventDetailsDataEventMatchStrategy';
import {GetEventDetailsDataEventMatchTeams} from './GetEventDetailsDataEventMatchTeams';

/**
 * The GetEventDetailsDataEventMatch model module.
 * @module model/GetEventDetailsDataEventMatch
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatch {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatch</code>.
   * @alias module:model/GetEventDetailsDataEventMatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatch} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatch} The populated <code>GetEventDetailsDataEventMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatch();
      if (data.hasOwnProperty('strategy'))
        obj.strategy = GetEventDetailsDataEventMatchStrategy.constructFromObject(data['strategy']);
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetEventDetailsDataEventMatchTeams]);
      if (data.hasOwnProperty('games'))
        obj.games = ApiClient.convertToType(data['games'], [GetEventDetailsDataEventMatchGames]);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetEventDetailsDataEventMatchStrategy} strategy
 */
GetEventDetailsDataEventMatch.prototype.strategy = undefined;

/**
 * @member {Array.<module:model/GetEventDetailsDataEventMatchTeams>} teams
 */
GetEventDetailsDataEventMatch.prototype.teams = undefined;

/**
 * @member {Array.<module:model/GetEventDetailsDataEventMatchGames>} games
 */
GetEventDetailsDataEventMatch.prototype.games = undefined;

