/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventMatchTeams1} from './GetEventDetailsDataEventMatchTeams1';
import {GetEventDetailsDataEventMatchVods} from './GetEventDetailsDataEventMatchVods';

/**
 * The GetEventDetailsDataEventMatchGames model module.
 * @module model/GetEventDetailsDataEventMatchGames
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatchGames {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatchGames</code>.
   * @alias module:model/GetEventDetailsDataEventMatchGames
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatchGames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatchGames} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatchGames} The populated <code>GetEventDetailsDataEventMatchGames</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatchGames();
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetEventDetailsDataEventMatchTeams1]);
      if (data.hasOwnProperty('vods'))
        obj.vods = ApiClient.convertToType(data['vods'], [GetEventDetailsDataEventMatchVods]);
    }
    return obj;
  }
}

/**
 * @member {Number} _number
 */
GetEventDetailsDataEventMatchGames.prototype._number = undefined;

/**
 * @member {String} id
 */
GetEventDetailsDataEventMatchGames.prototype.id = undefined;

/**
 * @member {String} state
 */
GetEventDetailsDataEventMatchGames.prototype.state = undefined;

/**
 * @member {Array.<module:model/GetEventDetailsDataEventMatchTeams1>} teams
 */
GetEventDetailsDataEventMatchGames.prototype.teams = undefined;

/**
 * @member {Array.<module:model/GetEventDetailsDataEventMatchVods>} vods
 */
GetEventDetailsDataEventMatchGames.prototype.vods = undefined;

