/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEvent} from './GetEventDetailsDataEvent';

/**
 * The GetEventDetailsData model module.
 * @module model/GetEventDetailsData
 * @version 1.0.0
 */
export class GetEventDetailsData {
  /**
   * Constructs a new <code>GetEventDetailsData</code>.
   * @alias module:model/GetEventDetailsData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsData} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsData} The populated <code>GetEventDetailsData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsData();
      if (data.hasOwnProperty('event'))
        obj.event = GetEventDetailsDataEvent.constructFromObject(data['event']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetEventDetailsDataEvent} event
 */
GetEventDetailsData.prototype.event = undefined;

