/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventListDataUnstartedMatchTeams} from './GetEventListDataUnstartedMatchTeams';

/**
 * The GetEventListDataUnstartedMatch model module.
 * @module model/GetEventListDataUnstartedMatch
 * @version 1.0.0
 */
export class GetEventListDataUnstartedMatch {
  /**
   * Constructs a new <code>GetEventListDataUnstartedMatch</code>.
   * @alias module:model/GetEventListDataUnstartedMatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventListDataUnstartedMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventListDataUnstartedMatch} obj Optional instance to populate.
   * @return {module:model/GetEventListDataUnstartedMatch} The populated <code>GetEventListDataUnstartedMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventListDataUnstartedMatch();
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetEventListDataUnstartedMatchTeams]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GetEventListDataUnstartedMatchTeams>} teams
 */
GetEventListDataUnstartedMatch.prototype.teams = undefined;

