/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventLeague} from './GetEventDetailsDataEventLeague';
import {GetEventListDataUnstartedMatch} from './GetEventListDataUnstartedMatch';

/**
 * The GetEventListDataUnstartedEvents model module.
 * @module model/GetEventListDataUnstartedEvents
 * @version 1.0.0
 */
export class GetEventListDataUnstartedEvents {
  /**
   * Constructs a new <code>GetEventListDataUnstartedEvents</code>.
   * @alias module:model/GetEventListDataUnstartedEvents
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventListDataUnstartedEvents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventListDataUnstartedEvents} obj Optional instance to populate.
   * @return {module:model/GetEventListDataUnstartedEvents} The populated <code>GetEventListDataUnstartedEvents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventListDataUnstartedEvents();
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'String');
      if (data.hasOwnProperty('match'))
        obj.match = GetEventListDataUnstartedMatch.constructFromObject(data['match']);
      if (data.hasOwnProperty('league'))
        obj.league = GetEventDetailsDataEventLeague.constructFromObject(data['league']);
    }
    return obj;
  }
}

/**
 * @member {String} startTime
 */
GetEventListDataUnstartedEvents.prototype.startTime = undefined;

/**
 * @member {module:model/GetEventListDataUnstartedMatch} match
 */
GetEventListDataUnstartedEvents.prototype.match = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventLeague} league
 */
GetEventListDataUnstartedEvents.prototype.league = undefined;

