/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventListDataUnstartedEvents} from './GetEventListDataUnstartedEvents';

/**
 * The GetEventListDataUnstarted model module.
 * @module model/GetEventListDataUnstarted
 * @version 1.0.0
 */
export class GetEventListDataUnstarted {
  /**
   * Constructs a new <code>GetEventListDataUnstarted</code>.
   * @alias module:model/GetEventListDataUnstarted
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventListDataUnstarted</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventListDataUnstarted} obj Optional instance to populate.
   * @return {module:model/GetEventListDataUnstarted} The populated <code>GetEventListDataUnstarted</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventListDataUnstarted();
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [GetEventListDataUnstartedEvents]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GetEventListDataUnstartedEvents>} events
 */
GetEventListDataUnstarted.prototype.events = undefined;

