/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventListDataInProgress model module.
 * @module model/GetEventListDataInProgress
 * @version 1.0.0
 */
export class GetEventListDataInProgress {
  /**
   * Constructs a new <code>GetEventListDataInProgress</code>.
   * @alias module:model/GetEventListDataInProgress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventListDataInProgress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventListDataInProgress} obj Optional instance to populate.
   * @return {module:model/GetEventListDataInProgress} The populated <code>GetEventListDataInProgress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventListDataInProgress();
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {Array.<Object>} events
 */
GetEventListDataInProgress.prototype.events = undefined;

