/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventDetailsDataEventMatchMediaLocale model module.
 * @module model/GetEventDetailsDataEventMatchMediaLocale
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatchMediaLocale {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatchMediaLocale</code>.
   * @alias module:model/GetEventDetailsDataEventMatchMediaLocale
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatchMediaLocale</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatchMediaLocale} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatchMediaLocale} The populated <code>GetEventDetailsDataEventMatchMediaLocale</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatchMediaLocale();
      if (data.hasOwnProperty('locale'))
        obj.locale = ApiClient.convertToType(data['locale'], 'String');
      if (data.hasOwnProperty('englishName'))
        obj.englishName = ApiClient.convertToType(data['englishName'], 'String');
      if (data.hasOwnProperty('translatedName'))
        obj.translatedName = ApiClient.convertToType(data['translatedName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} locale
 */
GetEventDetailsDataEventMatchMediaLocale.prototype.locale = undefined;

/**
 * @member {String} englishName
 */
GetEventDetailsDataEventMatchMediaLocale.prototype.englishName = undefined;

/**
 * @member {String} translatedName
 */
GetEventDetailsDataEventMatchMediaLocale.prototype.translatedName = undefined;

