/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventDetailsDataEventMatchTeams1 model module.
 * @module model/GetEventDetailsDataEventMatchTeams1
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatchTeams1 {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatchTeams1</code>.
   * @alias module:model/GetEventDetailsDataEventMatchTeams1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatchTeams1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatchTeams1} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatchTeams1} The populated <code>GetEventDetailsDataEventMatchTeams1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatchTeams1();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('side'))
        obj.side = ApiClient.convertToType(data['side'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetEventDetailsDataEventMatchTeams1.prototype.id = undefined;

/**
 * @member {String} side
 */
GetEventDetailsDataEventMatchTeams1.prototype.side = undefined;

