/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventLeague} from './GetEventDetailsDataEventLeague';
import {GetEventDetailsDataEventMatch} from './GetEventDetailsDataEventMatch';
import {GetEventDetailsDataEventTournament} from './GetEventDetailsDataEventTournament';

/**
 * The GetEventDetailsDataEvent model module.
 * @module model/GetEventDetailsDataEvent
 * @version 1.0.0
 */
export class GetEventDetailsDataEvent {
  /**
   * Constructs a new <code>GetEventDetailsDataEvent</code>.
   * @alias module:model/GetEventDetailsDataEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEvent} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEvent} The populated <code>GetEventDetailsDataEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEvent();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('tournament'))
        obj.tournament = GetEventDetailsDataEventTournament.constructFromObject(data['tournament']);
      if (data.hasOwnProperty('league'))
        obj.league = GetEventDetailsDataEventLeague.constructFromObject(data['league']);
      if (data.hasOwnProperty('match'))
        obj.match = GetEventDetailsDataEventMatch.constructFromObject(data['match']);
      if (data.hasOwnProperty('streams'))
        obj.streams = ApiClient.convertToType(data['streams'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetEventDetailsDataEvent.prototype.id = undefined;

/**
 * @member {String} type
 */
GetEventDetailsDataEvent.prototype.type = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventTournament} tournament
 */
GetEventDetailsDataEvent.prototype.tournament = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventLeague} league
 */
GetEventDetailsDataEvent.prototype.league = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventMatch} match
 */
GetEventDetailsDataEvent.prototype.match = undefined;

/**
 * @member {Array.<Object>} streams
 */
GetEventDetailsDataEvent.prototype.streams = undefined;

