/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventMatchResult} from './GetEventDetailsDataEventMatchResult';

/**
 * The GetEventDetailsDataEventMatchTeams model module.
 * @module model/GetEventDetailsDataEventMatchTeams
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatchTeams {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatchTeams</code>.
   * @alias module:model/GetEventDetailsDataEventMatchTeams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatchTeams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatchTeams} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatchTeams} The populated <code>GetEventDetailsDataEventMatchTeams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatchTeams();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = GetEventDetailsDataEventMatchResult.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetEventDetailsDataEventMatchTeams.prototype.id = undefined;

/**
 * @member {String} name
 */
GetEventDetailsDataEventMatchTeams.prototype.name = undefined;

/**
 * @member {String} code
 */
GetEventDetailsDataEventMatchTeams.prototype.code = undefined;

/**
 * @member {String} image
 */
GetEventDetailsDataEventMatchTeams.prototype.image = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventMatchResult} result
 */
GetEventDetailsDataEventMatchTeams.prototype.result = undefined;

