/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventDetailsDataEventMatchStrategy model module.
 * @module model/GetEventDetailsDataEventMatchStrategy
 * @version 1.0.0
 */
export class GetEventDetailsDataEventMatchStrategy {
  /**
   * Constructs a new <code>GetEventDetailsDataEventMatchStrategy</code>.
   * @alias module:model/GetEventDetailsDataEventMatchStrategy
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventMatchStrategy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventMatchStrategy} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventMatchStrategy} The populated <code>GetEventDetailsDataEventMatchStrategy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventMatchStrategy();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} count
 */
GetEventDetailsDataEventMatchStrategy.prototype.count = undefined;

