/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetEventDetailsDataEventLeague model module.
 * @module model/GetEventDetailsDataEventLeague
 * @version 1.0.0
 */
export class GetEventDetailsDataEventLeague {
  /**
   * Constructs a new <code>GetEventDetailsDataEventLeague</code>.
   * @alias module:model/GetEventDetailsDataEventLeague
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetEventDetailsDataEventLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetEventDetailsDataEventLeague} obj Optional instance to populate.
   * @return {module:model/GetEventDetailsDataEventLeague} The populated <code>GetEventDetailsDataEventLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetEventDetailsDataEventLeague();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetEventDetailsDataEventLeague.prototype.id = undefined;

/**
 * @member {String} slug
 */
GetEventDetailsDataEventLeague.prototype.slug = undefined;

/**
 * @member {String} image
 */
GetEventDetailsDataEventLeague.prototype.image = undefined;

/**
 * @member {String} name
 */
GetEventDetailsDataEventLeague.prototype.name = undefined;

