/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventListDataInProgress} from './GetEventListDataInProgress';

/**
 * The GetLiveDetailsData model module.
 * @module model/GetLiveDetailsData
 * @version 1.0.0
 */
export class GetLiveDetailsData {
  /**
   * Constructs a new <code>GetLiveDetailsData</code>.
   * @alias module:model/GetLiveDetailsData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetLiveDetailsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLiveDetailsData} obj Optional instance to populate.
   * @return {module:model/GetLiveDetailsData} The populated <code>GetLiveDetailsData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLiveDetailsData();
      if (data.hasOwnProperty('schedule'))
        obj.schedule = GetEventListDataInProgress.constructFromObject(data['schedule']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetEventListDataInProgress} schedule
 */
GetLiveDetailsData.prototype.schedule = undefined;

