/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetLiveDetailsData} from './GetLiveDetailsData';

/**
 * The GetLiveDetails model module.
 * @module model/GetLiveDetails
 * @version 1.0.0
 */
export class GetLiveDetails {
  /**
   * Constructs a new <code>GetLiveDetails</code>.
   * @alias module:model/GetLiveDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetLiveDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLiveDetails} obj Optional instance to populate.
   * @return {module:model/GetLiveDetails} The populated <code>GetLiveDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLiveDetails();
      if (data.hasOwnProperty('data'))
        obj.data = GetLiveDetailsData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetLiveDetailsData} data
 */
GetLiveDetails.prototype.data = undefined;

