/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetLeaguesDataDisplayPriority model module.
 * @module model/GetLeaguesDataDisplayPriority
 * @version 1.0.0
 */
export class GetLeaguesDataDisplayPriority {
  /**
   * Constructs a new <code>GetLeaguesDataDisplayPriority</code>.
   * @alias module:model/GetLeaguesDataDisplayPriority
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetLeaguesDataDisplayPriority</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLeaguesDataDisplayPriority} obj Optional instance to populate.
   * @return {module:model/GetLeaguesDataDisplayPriority} The populated <code>GetLeaguesDataDisplayPriority</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLeaguesDataDisplayPriority();
      if (data.hasOwnProperty('position'))
        obj.position = ApiClient.convertToType(data['position'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} position
 */
GetLeaguesDataDisplayPriority.prototype.position = undefined;

/**
 * @member {String} status
 */
GetLeaguesDataDisplayPriority.prototype.status = undefined;

