/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventTournament} from './GetEventDetailsDataEventTournament';
import {GetLeaguesForStandingsDataSeason} from './GetLeaguesForStandingsDataSeason';

/**
 * The GetLeaguesForStandingsDataTournaments model module.
 * @module model/GetLeaguesForStandingsDataTournaments
 * @version 1.0.0
 */
export class GetLeaguesForStandingsDataTournaments {
  /**
   * Constructs a new <code>GetLeaguesForStandingsDataTournaments</code>.
   * @alias module:model/GetLeaguesForStandingsDataTournaments
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetLeaguesForStandingsDataTournaments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLeaguesForStandingsDataTournaments} obj Optional instance to populate.
   * @return {module:model/GetLeaguesForStandingsDataTournaments} The populated <code>GetLeaguesForStandingsDataTournaments</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLeaguesForStandingsDataTournaments();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('split'))
        obj.split = GetEventDetailsDataEventTournament.constructFromObject(data['split']);
      if (data.hasOwnProperty('season'))
        obj.season = GetLeaguesForStandingsDataSeason.constructFromObject(data['season']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetLeaguesForStandingsDataTournaments.prototype.id = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventTournament} split
 */
GetLeaguesForStandingsDataTournaments.prototype.split = undefined;

/**
 * @member {module:model/GetLeaguesForStandingsDataSeason} season
 */
GetLeaguesForStandingsDataTournaments.prototype.season = undefined;

