/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetLeaguesDataDisplayPriority} from './GetLeaguesDataDisplayPriority';

/**
 * The GetLeaguesDataLeagues model module.
 * @module model/GetLeaguesDataLeagues
 * @version 1.0.0
 */
export class GetLeaguesDataLeagues {
  /**
   * Constructs a new <code>GetLeaguesDataLeagues</code>.
   * @alias module:model/GetLeaguesDataLeagues
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetLeaguesDataLeagues</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLeaguesDataLeagues} obj Optional instance to populate.
   * @return {module:model/GetLeaguesDataLeagues} The populated <code>GetLeaguesDataLeagues</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLeaguesDataLeagues();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'Number');
      if (data.hasOwnProperty('displayPriority'))
        obj.displayPriority = GetLeaguesDataDisplayPriority.constructFromObject(data['displayPriority']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetLeaguesDataLeagues.prototype.id = undefined;

/**
 * @member {String} slug
 */
GetLeaguesDataLeagues.prototype.slug = undefined;

/**
 * @member {String} name
 */
GetLeaguesDataLeagues.prototype.name = undefined;

/**
 * @member {String} region
 */
GetLeaguesDataLeagues.prototype.region = undefined;

/**
 * @member {String} image
 */
GetLeaguesDataLeagues.prototype.image = undefined;

/**
 * @member {Number} priority
 */
GetLeaguesDataLeagues.prototype.priority = undefined;

/**
 * @member {module:model/GetLeaguesDataDisplayPriority} displayPriority
 */
GetLeaguesDataLeagues.prototype.displayPriority = undefined;

