/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleDataSchedule} from './GetScheduleDataSchedule';

/**
 * The GetScheduleData model module.
 * @module model/GetScheduleData
 * @version 1.0.0
 */
export class GetScheduleData {
  /**
   * Constructs a new <code>GetScheduleData</code>.
   * @alias module:model/GetScheduleData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleData} obj Optional instance to populate.
   * @return {module:model/GetScheduleData} The populated <code>GetScheduleData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleData();
      if (data.hasOwnProperty('schedule'))
        obj.schedule = GetScheduleDataSchedule.constructFromObject(data['schedule']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetScheduleDataSchedule} schedule
 */
GetScheduleData.prototype.schedule = undefined;

