/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataColumns} from './GetStandingsDataColumns';

/**
 * The GetStandingsDataSections model module.
 * @module model/GetStandingsDataSections
 * @version 1.0.0
 */
export class GetStandingsDataSections {
  /**
   * Constructs a new <code>GetStandingsDataSections</code>.
   * @alias module:model/GetStandingsDataSections
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataSections</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataSections} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataSections} The populated <code>GetStandingsDataSections</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataSections();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('columns'))
        obj.columns = ApiClient.convertToType(data['columns'], [GetStandingsDataColumns]);
      if (data.hasOwnProperty('rankings'))
        obj.rankings = ApiClient.convertToType(data['rankings'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetStandingsDataSections.prototype.id = undefined;

/**
 * @member {String} name
 */
GetStandingsDataSections.prototype.name = undefined;

/**
 * @member {String} type
 */
GetStandingsDataSections.prototype.type = undefined;

/**
 * @member {Array.<module:model/GetStandingsDataColumns>} columns
 */
GetStandingsDataSections.prototype.columns = undefined;

/**
 * @member {Array.<Object>} rankings
 */
GetStandingsDataSections.prototype.rankings = undefined;

