/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataMatches} from './GetStandingsDataMatches';

/**
 * The GetStandingsDataCells model module.
 * @module model/GetStandingsDataCells
 * @version 1.0.0
 */
export class GetStandingsDataCells {
  /**
   * Constructs a new <code>GetStandingsDataCells</code>.
   * @alias module:model/GetStandingsDataCells
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataCells</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataCells} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataCells} The populated <code>GetStandingsDataCells</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataCells();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('matches'))
        obj.matches = ApiClient.convertToType(data['matches'], [GetStandingsDataMatches]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetStandingsDataCells.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetStandingsDataCells.prototype.slug = undefined;

/**
 * @member {Array.<module:model/GetStandingsDataMatches>} matches
 */
GetStandingsDataCells.prototype.matches = undefined;

