/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetScheduleDataScheduleMatchResult model module.
 * @module model/GetScheduleDataScheduleMatchResult
 * @version 1.0.0
 */
export class GetScheduleDataScheduleMatchResult {
  /**
   * Constructs a new <code>GetScheduleDataScheduleMatchResult</code>.
   * @alias module:model/GetScheduleDataScheduleMatchResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleMatchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleMatchResult} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleMatchResult} The populated <code>GetScheduleDataScheduleMatchResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleMatchResult();
      if (data.hasOwnProperty('outcome'))
        obj.outcome = ApiClient.convertToType(data['outcome'], 'String');
      if (data.hasOwnProperty('gameWins'))
        obj.gameWins = ApiClient.convertToType(data['gameWins'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} outcome
 */
GetScheduleDataScheduleMatchResult.prototype.outcome = undefined;

/**
 * @member {Number} gameWins
 */
GetScheduleDataScheduleMatchResult.prototype.gameWins = undefined;

