/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataTeams} from './GetStandingsDataTeams';

/**
 * The GetStandingsDataMatches model module.
 * @module model/GetStandingsDataMatches
 * @version 1.0.0
 */
export class GetStandingsDataMatches {
  /**
   * Constructs a new <code>GetStandingsDataMatches</code>.
   * @alias module:model/GetStandingsDataMatches
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataMatches</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataMatches} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataMatches} The populated <code>GetStandingsDataMatches</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataMatches();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('structuralId'))
        obj.structuralId = ApiClient.convertToType(data['structuralId'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetStandingsDataTeams]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetStandingsDataMatches.prototype.id = undefined;

/**
 * @member {String} structuralId
 */
GetStandingsDataMatches.prototype.structuralId = undefined;

/**
 * @member {String} state
 */
GetStandingsDataMatches.prototype.state = undefined;

/**
 * @member {Array.<module:model/GetStandingsDataTeams>} teams
 */
GetStandingsDataMatches.prototype.teams = undefined;

