/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleData} from './GetScheduleData';

/**
 * The GetSchedule model module.
 * @module model/GetSchedule
 * @version 1.0.0
 */
export class GetSchedule {
  /**
   * Constructs a new <code>GetSchedule</code>.
   * @alias module:model/GetSchedule
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetSchedule} obj Optional instance to populate.
   * @return {module:model/GetSchedule} The populated <code>GetSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetSchedule();
      if (data.hasOwnProperty('data'))
        obj.data = GetScheduleData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetScheduleData} data
 */
GetSchedule.prototype.data = undefined;

