/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsData} from './GetStandingsData';

/**
 * The GetStandings model module.
 * @module model/GetStandings
 * @version 1.0.0
 */
export class GetStandings {
  /**
   * Constructs a new <code>GetStandings</code>.
   * @alias module:model/GetStandings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandings} obj Optional instance to populate.
   * @return {module:model/GetStandings} The populated <code>GetStandings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandings();
      if (data.hasOwnProperty('data'))
        obj.data = GetStandingsData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetStandingsData} data
 */
GetStandings.prototype.data = undefined;

