/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataOrigin} from './GetStandingsDataOrigin';
import {GetStandingsDataResult} from './GetStandingsDataResult';

/**
 * The GetStandingsDataTeams model module.
 * @module model/GetStandingsDataTeams
 * @version 1.0.0
 */
export class GetStandingsDataTeams {
  /**
   * Constructs a new <code>GetStandingsDataTeams</code>.
   * @alias module:model/GetStandingsDataTeams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataTeams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataTeams} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataTeams} The populated <code>GetStandingsDataTeams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataTeams();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = GetStandingsDataResult.constructFromObject(data['result']);
      if (data.hasOwnProperty('origin'))
        obj.origin = GetStandingsDataOrigin.constructFromObject(data['origin']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetStandingsDataTeams.prototype.id = undefined;

/**
 * @member {String} slug
 */
GetStandingsDataTeams.prototype.slug = undefined;

/**
 * @member {String} name
 */
GetStandingsDataTeams.prototype.name = undefined;

/**
 * @member {String} code
 */
GetStandingsDataTeams.prototype.code = undefined;

/**
 * @member {String} image
 */
GetStandingsDataTeams.prototype.image = undefined;

/**
 * @member {module:model/GetStandingsDataResult} result
 */
GetStandingsDataTeams.prototype.result = undefined;

/**
 * @member {module:model/GetStandingsDataOrigin} origin
 */
GetStandingsDataTeams.prototype.origin = undefined;

