/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetStandingsDataSeasonSplits model module.
 * @module model/GetStandingsDataSeasonSplits
 * @version 1.0.0
 */
export class GetStandingsDataSeasonSplits {
  /**
   * Constructs a new <code>GetStandingsDataSeasonSplits</code>.
   * @alias module:model/GetStandingsDataSeasonSplits
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataSeasonSplits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataSeasonSplits} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataSeasonSplits} The populated <code>GetStandingsDataSeasonSplits</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataSeasonSplits();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'String');
      if (data.hasOwnProperty('endTime'))
        obj.endTime = ApiClient.convertToType(data['endTime'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetStandingsDataSeasonSplits.prototype.id = undefined;

/**
 * @member {String} name
 */
GetStandingsDataSeasonSplits.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetStandingsDataSeasonSplits.prototype.slug = undefined;

/**
 * @member {String} startTime
 */
GetStandingsDataSeasonSplits.prototype.startTime = undefined;

/**
 * @member {String} endTime
 */
GetStandingsDataSeasonSplits.prototype.endTime = undefined;

