/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataStandings} from './GetStandingsDataStandings';

/**
 * The GetStandingsData model module.
 * @module model/GetStandingsData
 * @version 1.0.0
 */
export class GetStandingsData {
  /**
   * Constructs a new <code>GetStandingsData</code>.
   * @alias module:model/GetStandingsData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsData} obj Optional instance to populate.
   * @return {module:model/GetStandingsData} The populated <code>GetStandingsData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsData();
      if (data.hasOwnProperty('standings'))
        obj.standings = ApiClient.convertToType(data['standings'], [GetStandingsDataStandings]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GetStandingsDataStandings>} standings
 */
GetStandingsData.prototype.standings = undefined;

