/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetScheduleDataScheduleLeague model module.
 * @module model/GetScheduleDataScheduleLeague
 * @version 1.0.0
 */
export class GetScheduleDataScheduleLeague {
  /**
   * Constructs a new <code>GetScheduleDataScheduleLeague</code>.
   * @alias module:model/GetScheduleDataScheduleLeague
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleLeague} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleLeague} The populated <code>GetScheduleDataScheduleLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleLeague();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetScheduleDataScheduleLeague.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetScheduleDataScheduleLeague.prototype.slug = undefined;

/**
 * @member {String} image
 */
GetScheduleDataScheduleLeague.prototype.image = undefined;

/**
 * @member {String} region
 */
GetScheduleDataScheduleLeague.prototype.region = undefined;

