/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleDataScheduleMatchStrategy} from './GetScheduleDataScheduleMatchStrategy';
import {GetScheduleDataScheduleMatchTeams} from './GetScheduleDataScheduleMatchTeams';

/**
 * The GetScheduleDataScheduleMatch model module.
 * @module model/GetScheduleDataScheduleMatch
 * @version 1.0.0
 */
export class GetScheduleDataScheduleMatch {
  /**
   * Constructs a new <code>GetScheduleDataScheduleMatch</code>.
   * @alias module:model/GetScheduleDataScheduleMatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleMatch} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleMatch} The populated <code>GetScheduleDataScheduleMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleMatch();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('flags'))
        obj.flags = ApiClient.convertToType(data['flags'], ['String']);
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetScheduleDataScheduleMatchTeams]);
      if (data.hasOwnProperty('strategy'))
        obj.strategy = GetScheduleDataScheduleMatchStrategy.constructFromObject(data['strategy']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetScheduleDataScheduleMatch.prototype.id = undefined;

/**
 * @member {Array.<String>} flags
 */
GetScheduleDataScheduleMatch.prototype.flags = undefined;

/**
 * @member {Array.<module:model/GetScheduleDataScheduleMatchTeams>} teams
 */
GetScheduleDataScheduleMatch.prototype.teams = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleMatchStrategy} strategy
 */
GetScheduleDataScheduleMatch.prototype.strategy = undefined;

