/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleDataScheduleTournamentSplit} from './GetScheduleDataScheduleTournamentSplit';

/**
 * The GetScheduleDataScheduleTournament model module.
 * @module model/GetScheduleDataScheduleTournament
 * @version 1.0.0
 */
export class GetScheduleDataScheduleTournament {
  /**
   * Constructs a new <code>GetScheduleDataScheduleTournament</code>.
   * @alias module:model/GetScheduleDataScheduleTournament
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleTournament</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleTournament} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleTournament} The populated <code>GetScheduleDataScheduleTournament</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleTournament();
      if (data.hasOwnProperty('split'))
        obj.split = GetScheduleDataScheduleTournamentSplit.constructFromObject(data['split']);
      if (data.hasOwnProperty('season'))
        obj.season = GetScheduleDataScheduleTournamentSplit.constructFromObject(data['season']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetScheduleDataScheduleTournamentSplit} split
 */
GetScheduleDataScheduleTournament.prototype.split = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleTournamentSplit} season
 */
GetScheduleDataScheduleTournament.prototype.season = undefined;

