/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetScheduleDataSchedulePages model module.
 * @module model/GetScheduleDataSchedulePages
 * @version 1.0.0
 */
export class GetScheduleDataSchedulePages {
  /**
   * Constructs a new <code>GetScheduleDataSchedulePages</code>.
   * @alias module:model/GetScheduleDataSchedulePages
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataSchedulePages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataSchedulePages} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataSchedulePages} The populated <code>GetScheduleDataSchedulePages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataSchedulePages();
      if (data.hasOwnProperty('older'))
        obj.older = ApiClient.convertToType(data['older'], 'String');
      if (data.hasOwnProperty('newer'))
        obj.newer = ApiClient.convertToType(data['newer'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} older
 */
GetScheduleDataSchedulePages.prototype.older = undefined;

/**
 * @member {String} newer
 */
GetScheduleDataSchedulePages.prototype.newer = undefined;

