/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetStandingsDataOrigin model module.
 * @module model/GetStandingsDataOrigin
 * @version 1.0.0
 */
export class GetStandingsDataOrigin {
  /**
   * Constructs a new <code>GetStandingsDataOrigin</code>.
   * @alias module:model/GetStandingsDataOrigin
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataOrigin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataOrigin} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataOrigin} The populated <code>GetStandingsDataOrigin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataOrigin();
      if (data.hasOwnProperty('structuralId'))
        obj.structuralId = ApiClient.convertToType(data['structuralId'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('slot'))
        obj.slot = ApiClient.convertToType(data['slot'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} structuralId
 */
GetStandingsDataOrigin.prototype.structuralId = undefined;

/**
 * @member {String} type
 */
GetStandingsDataOrigin.prototype.type = undefined;

/**
 * @member {Number} slot
 */
GetStandingsDataOrigin.prototype.slot = undefined;

