/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetScheduleDataScheduleMatchRecord model module.
 * @module model/GetScheduleDataScheduleMatchRecord
 * @version 1.0.0
 */
export class GetScheduleDataScheduleMatchRecord {
  /**
   * Constructs a new <code>GetScheduleDataScheduleMatchRecord</code>.
   * @alias module:model/GetScheduleDataScheduleMatchRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleMatchRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleMatchRecord} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleMatchRecord} The populated <code>GetScheduleDataScheduleMatchRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleMatchRecord();
      if (data.hasOwnProperty('wins'))
        obj.wins = ApiClient.convertToType(data['wins'], 'Number');
      if (data.hasOwnProperty('losses'))
        obj.losses = ApiClient.convertToType(data['losses'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} wins
 */
GetScheduleDataScheduleMatchRecord.prototype.wins = undefined;

/**
 * @member {Number} losses
 */
GetScheduleDataScheduleMatchRecord.prototype.losses = undefined;

