/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetStandingsDataSections} from './GetStandingsDataSections';

/**
 * The GetStandingsDataStages model module.
 * @module model/GetStandingsDataStages
 * @version 1.0.0
 */
export class GetStandingsDataStages {
  /**
   * Constructs a new <code>GetStandingsDataStages</code>.
   * @alias module:model/GetStandingsDataStages
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataStages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataStages} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataStages} The populated <code>GetStandingsDataStages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataStages();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('sections'))
        obj.sections = ApiClient.convertToType(data['sections'], [GetStandingsDataSections]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetStandingsDataStages.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetStandingsDataStages.prototype.slug = undefined;

/**
 * @member {Array.<module:model/GetStandingsDataSections>} sections
 */
GetStandingsDataStages.prototype.sections = undefined;

