/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleDataScheduleLeague} from './GetScheduleDataScheduleLeague';
import {GetScheduleDataScheduleMatch} from './GetScheduleDataScheduleMatch';
import {GetScheduleDataScheduleTournament} from './GetScheduleDataScheduleTournament';

/**
 * The GetScheduleDataScheduleEvents model module.
 * @module model/GetScheduleDataScheduleEvents
 * @version 1.0.0
 */
export class GetScheduleDataScheduleEvents {
  /**
   * Constructs a new <code>GetScheduleDataScheduleEvents</code>.
   * @alias module:model/GetScheduleDataScheduleEvents
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleEvents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleEvents} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleEvents} The populated <code>GetScheduleDataScheduleEvents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleEvents();
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('blockName'))
        obj.blockName = ApiClient.convertToType(data['blockName'], 'String');
      if (data.hasOwnProperty('league'))
        obj.league = GetScheduleDataScheduleLeague.constructFromObject(data['league']);
      if (data.hasOwnProperty('tournament'))
        obj.tournament = GetScheduleDataScheduleTournament.constructFromObject(data['tournament']);
      if (data.hasOwnProperty('match'))
        obj.match = GetScheduleDataScheduleMatch.constructFromObject(data['match']);
    }
    return obj;
  }
}

/**
 * @member {String} startTime
 */
GetScheduleDataScheduleEvents.prototype.startTime = undefined;

/**
 * @member {String} state
 */
GetScheduleDataScheduleEvents.prototype.state = undefined;

/**
 * @member {String} type
 */
GetScheduleDataScheduleEvents.prototype.type = undefined;

/**
 * @member {String} blockName
 */
GetScheduleDataScheduleEvents.prototype.blockName = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleLeague} league
 */
GetScheduleDataScheduleEvents.prototype.league = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleTournament} tournament
 */
GetScheduleDataScheduleEvents.prototype.tournament = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleMatch} match
 */
GetScheduleDataScheduleEvents.prototype.match = undefined;

