/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetScheduleDataScheduleMatchRecord} from './GetScheduleDataScheduleMatchRecord';
import {GetScheduleDataScheduleMatchResult} from './GetScheduleDataScheduleMatchResult';

/**
 * The GetScheduleDataScheduleMatchTeams model module.
 * @module model/GetScheduleDataScheduleMatchTeams
 * @version 1.0.0
 */
export class GetScheduleDataScheduleMatchTeams {
  /**
   * Constructs a new <code>GetScheduleDataScheduleMatchTeams</code>.
   * @alias module:model/GetScheduleDataScheduleMatchTeams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetScheduleDataScheduleMatchTeams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetScheduleDataScheduleMatchTeams} obj Optional instance to populate.
   * @return {module:model/GetScheduleDataScheduleMatchTeams} The populated <code>GetScheduleDataScheduleMatchTeams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetScheduleDataScheduleMatchTeams();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = GetScheduleDataScheduleMatchResult.constructFromObject(data['result']);
      if (data.hasOwnProperty('record'))
        obj.record = GetScheduleDataScheduleMatchRecord.constructFromObject(data['record']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetScheduleDataScheduleMatchTeams.prototype.name = undefined;

/**
 * @member {String} code
 */
GetScheduleDataScheduleMatchTeams.prototype.code = undefined;

/**
 * @member {String} image
 */
GetScheduleDataScheduleMatchTeams.prototype.image = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleMatchResult} result
 */
GetScheduleDataScheduleMatchTeams.prototype.result = undefined;

/**
 * @member {module:model/GetScheduleDataScheduleMatchRecord} record
 */
GetScheduleDataScheduleMatchTeams.prototype.record = undefined;

