/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventTournament} from './GetEventDetailsDataEventTournament';
import {GetStandingsDataSeason} from './GetStandingsDataSeason';
import {GetStandingsDataStages} from './GetStandingsDataStages';

/**
 * The GetStandingsDataStandings model module.
 * @module model/GetStandingsDataStandings
 * @version 1.0.0
 */
export class GetStandingsDataStandings {
  /**
   * Constructs a new <code>GetStandingsDataStandings</code>.
   * @alias module:model/GetStandingsDataStandings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetStandingsDataStandings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetStandingsDataStandings} obj Optional instance to populate.
   * @return {module:model/GetStandingsDataStandings} The populated <code>GetStandingsDataStandings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetStandingsDataStandings();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('scores'))
        obj.scores = ApiClient.convertToType(data['scores'], Object);
      if (data.hasOwnProperty('split'))
        obj.split = GetEventDetailsDataEventTournament.constructFromObject(data['split']);
      if (data.hasOwnProperty('season'))
        obj.season = GetStandingsDataSeason.constructFromObject(data['season']);
      if (data.hasOwnProperty('stages'))
        obj.stages = ApiClient.convertToType(data['stages'], [GetStandingsDataStages]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetStandingsDataStandings.prototype.id = undefined;

/**
 * @member {String} name
 */
GetStandingsDataStandings.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetStandingsDataStandings.prototype.slug = undefined;

/**
 * @member {Object} scores
 */
GetStandingsDataStandings.prototype.scores = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventTournament} split
 */
GetStandingsDataStandings.prototype.split = undefined;

/**
 * @member {module:model/GetStandingsDataSeason} season
 */
GetStandingsDataStandings.prototype.season = undefined;

/**
 * @member {Array.<module:model/GetStandingsDataStages>} stages
 */
GetStandingsDataStandings.prototype.stages = undefined;

