/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetVodsDataScheduleVods model module.
 * @module model/GetVodsDataScheduleVods
 * @version 1.0.0
 */
export class GetVodsDataScheduleVods {
  /**
   * Constructs a new <code>GetVodsDataScheduleVods</code>.
   * @alias module:model/GetVodsDataScheduleVods
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataScheduleVods</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataScheduleVods} obj Optional instance to populate.
   * @return {module:model/GetVodsDataScheduleVods} The populated <code>GetVodsDataScheduleVods</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataScheduleVods();
      if (data.hasOwnProperty('parameter'))
        obj.parameter = ApiClient.convertToType(data['parameter'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} parameter
 */
GetVodsDataScheduleVods.prototype.parameter = undefined;

