/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetVodsDataScheduleVods} from './GetVodsDataScheduleVods';

/**
 * The GetVodsDataScheduleGames model module.
 * @module model/GetVodsDataScheduleGames
 * @version 1.0.0
 */
export class GetVodsDataScheduleGames {
  /**
   * Constructs a new <code>GetVodsDataScheduleGames</code>.
   * @alias module:model/GetVodsDataScheduleGames
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataScheduleGames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataScheduleGames} obj Optional instance to populate.
   * @return {module:model/GetVodsDataScheduleGames} The populated <code>GetVodsDataScheduleGames</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataScheduleGames();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('vods'))
        obj.vods = ApiClient.convertToType(data['vods'], [GetVodsDataScheduleVods]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetVodsDataScheduleGames.prototype.id = undefined;

/**
 * @member {String} state
 */
GetVodsDataScheduleGames.prototype.state = undefined;

/**
 * @member {Array.<module:model/GetVodsDataScheduleVods>} vods
 */
GetVodsDataScheduleGames.prototype.vods = undefined;

