/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetVodsDataScheduleMatchStrategy} from './GetVodsDataScheduleMatchStrategy';
import {GetVodsDataScheduleMatchTeams} from './GetVodsDataScheduleMatchTeams';

/**
 * The GetVodsDataScheduleMatch model module.
 * @module model/GetVodsDataScheduleMatch
 * @version 1.0.0
 */
export class GetVodsDataScheduleMatch {
  /**
   * Constructs a new <code>GetVodsDataScheduleMatch</code>.
   * @alias module:model/GetVodsDataScheduleMatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataScheduleMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataScheduleMatch} obj Optional instance to populate.
   * @return {module:model/GetVodsDataScheduleMatch} The populated <code>GetVodsDataScheduleMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataScheduleMatch();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('flags'))
        obj.flags = ApiClient.convertToType(data['flags'], ['String']);
      if (data.hasOwnProperty('teams'))
        obj.teams = ApiClient.convertToType(data['teams'], [GetVodsDataScheduleMatchTeams]);
      if (data.hasOwnProperty('strategy'))
        obj.strategy = GetVodsDataScheduleMatchStrategy.constructFromObject(data['strategy']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetVodsDataScheduleMatch.prototype.id = undefined;

/**
 * @member {String} type
 */
GetVodsDataScheduleMatch.prototype.type = undefined;

/**
 * @member {Array.<String>} flags
 */
GetVodsDataScheduleMatch.prototype.flags = undefined;

/**
 * @member {Array.<module:model/GetVodsDataScheduleMatchTeams>} teams
 */
GetVodsDataScheduleMatch.prototype.teams = undefined;

/**
 * @member {module:model/GetVodsDataScheduleMatchStrategy} strategy
 */
GetVodsDataScheduleMatch.prototype.strategy = undefined;

