/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetVodsDataScheduleEvents} from './GetVodsDataScheduleEvents';

/**
 * The GetVodsDataSchedule model module.
 * @module model/GetVodsDataSchedule
 * @version 1.0.0
 */
export class GetVodsDataSchedule {
  /**
   * Constructs a new <code>GetVodsDataSchedule</code>.
   * @alias module:model/GetVodsDataSchedule
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataSchedule} obj Optional instance to populate.
   * @return {module:model/GetVodsDataSchedule} The populated <code>GetVodsDataSchedule</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataSchedule();
      if (data.hasOwnProperty('events'))
        obj.events = ApiClient.convertToType(data['events'], [GetVodsDataScheduleEvents]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GetVodsDataScheduleEvents>} events
 */
GetVodsDataSchedule.prototype.events = undefined;

