/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetVodsDataScheduleLeague model module.
 * @module model/GetVodsDataScheduleLeague
 * @version 1.0.0
 */
export class GetVodsDataScheduleLeague {
  /**
   * Constructs a new <code>GetVodsDataScheduleLeague</code>.
   * @alias module:model/GetVodsDataScheduleLeague
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataScheduleLeague</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataScheduleLeague} obj Optional instance to populate.
   * @return {module:model/GetVodsDataScheduleLeague} The populated <code>GetVodsDataScheduleLeague</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataScheduleLeague();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetVodsDataScheduleLeague.prototype.name = undefined;

/**
 * @member {String} slug
 */
GetVodsDataScheduleLeague.prototype.slug = undefined;

