/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetVodsData} from './GetVodsData';

/**
 * The GetVods model module.
 * @module model/GetVods
 * @version 1.0.0
 */
export class GetVods {
  /**
   * Constructs a new <code>GetVods</code>.
   * @alias module:model/GetVods
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVods</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVods} obj Optional instance to populate.
   * @return {module:model/GetVods} The populated <code>GetVods</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVods();
      if (data.hasOwnProperty('data'))
        obj.data = GetVodsData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GetVodsData} data
 */
GetVods.prototype.data = undefined;

