/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetEventDetailsDataEventMatchResult} from './GetEventDetailsDataEventMatchResult';

/**
 * The GetVodsDataScheduleMatchTeams model module.
 * @module model/GetVodsDataScheduleMatchTeams
 * @version 1.0.0
 */
export class GetVodsDataScheduleMatchTeams {
  /**
   * Constructs a new <code>GetVodsDataScheduleMatchTeams</code>.
   * @alias module:model/GetVodsDataScheduleMatchTeams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetVodsDataScheduleMatchTeams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetVodsDataScheduleMatchTeams} obj Optional instance to populate.
   * @return {module:model/GetVodsDataScheduleMatchTeams} The populated <code>GetVodsDataScheduleMatchTeams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetVodsDataScheduleMatchTeams();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = GetEventDetailsDataEventMatchResult.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetVodsDataScheduleMatchTeams.prototype.name = undefined;

/**
 * @member {String} code
 */
GetVodsDataScheduleMatchTeams.prototype.code = undefined;

/**
 * @member {String} image
 */
GetVodsDataScheduleMatchTeams.prototype.image = undefined;

/**
 * @member {module:model/GetEventDetailsDataEventMatchResult} result
 */
GetVodsDataScheduleMatchTeams.prototype.result = undefined;

