/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ValorantEsportsOpenApiSpecification);
  }
}(this, function(expect, ValorantEsportsOpenApiSpecification) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetEventDetailsDataEvent', function() {
      beforeEach(function() {
        instance = new ValorantEsportsOpenApiSpecification.GetEventDetailsDataEvent();
      });

      it('should create an instance of GetEventDetailsDataEvent', function() {
        // TODO: update the code to test GetEventDetailsDataEvent
        expect(instance).to.be.a(ValorantEsportsOpenApiSpecification.GetEventDetailsDataEvent);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property tournament (base name: "tournament")', function() {
        // TODO: update the code to test the property tournament
        expect(instance).to.have.property('tournament');
        // expect(instance.tournament).to.be(expectedValueLiteral);
      });

      it('should have the property league (base name: "league")', function() {
        // TODO: update the code to test the property league
        expect(instance).to.have.property('league');
        // expect(instance.league).to.be(expectedValueLiteral);
      });

      it('should have the property match (base name: "match")', function() {
        // TODO: update the code to test the property match
        expect(instance).to.have.property('match');
        // expect(instance.match).to.be(expectedValueLiteral);
      });

      it('should have the property streams (base name: "streams")', function() {
        // TODO: update the code to test the property streams
        expect(instance).to.have.property('streams');
        // expect(instance.streams).to.be(expectedValueLiteral);
      });

    });
  });

}));
