/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ValorantEsportsOpenApiSpecification);
  }
}(this, function(expect, ValorantEsportsOpenApiSpecification) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetEventListDataUnstartedEvents', function() {
      beforeEach(function() {
        instance = new ValorantEsportsOpenApiSpecification.GetEventListDataUnstartedEvents();
      });

      it('should create an instance of GetEventListDataUnstartedEvents', function() {
        // TODO: update the code to test GetEventListDataUnstartedEvents
        expect(instance).to.be.a(ValorantEsportsOpenApiSpecification.GetEventListDataUnstartedEvents);
      });

      it('should have the property startTime (base name: "startTime")', function() {
        // TODO: update the code to test the property startTime
        expect(instance).to.have.property('startTime');
        // expect(instance.startTime).to.be(expectedValueLiteral);
      });

      it('should have the property match (base name: "match")', function() {
        // TODO: update the code to test the property match
        expect(instance).to.have.property('match');
        // expect(instance.match).to.be(expectedValueLiteral);
      });

      it('should have the property league (base name: "league")', function() {
        // TODO: update the code to test the property league
        expect(instance).to.have.property('league');
        // expect(instance.league).to.be(expectedValueLiteral);
      });

    });
  });

}));
