/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ValorantEsportsOpenApiSpecification);
  }
}(this, function(expect, ValorantEsportsOpenApiSpecification) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetEventDetailsDataEventMatch', function() {
      beforeEach(function() {
        instance = new ValorantEsportsOpenApiSpecification.GetEventDetailsDataEventMatch();
      });

      it('should create an instance of GetEventDetailsDataEventMatch', function() {
        // TODO: update the code to test GetEventDetailsDataEventMatch
        expect(instance).to.be.a(ValorantEsportsOpenApiSpecification.GetEventDetailsDataEventMatch);
      });

      it('should have the property strategy (base name: "strategy")', function() {
        // TODO: update the code to test the property strategy
        expect(instance).to.have.property('strategy');
        // expect(instance.strategy).to.be(expectedValueLiteral);
      });

      it('should have the property teams (base name: "teams")', function() {
        // TODO: update the code to test the property teams
        expect(instance).to.have.property('teams');
        // expect(instance.teams).to.be(expectedValueLiteral);
      });

      it('should have the property games (base name: "games")', function() {
        // TODO: update the code to test the property games
        expect(instance).to.have.property('games');
        // expect(instance.games).to.be(expectedValueLiteral);
      });

    });
  });

}));
