/*
 * ValorantEsports OpenApi Specification
 * Unofficial documentation to the ValorantEsports Api
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ValorantEsportsOpenApiSpecification);
  }
}(this, function(expect, ValorantEsportsOpenApiSpecification) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetEventDetailsDataEventMatchMediaLocale', function() {
      beforeEach(function() {
        instance = new ValorantEsportsOpenApiSpecification.GetEventDetailsDataEventMatchMediaLocale();
      });

      it('should create an instance of GetEventDetailsDataEventMatchMediaLocale', function() {
        // TODO: update the code to test GetEventDetailsDataEventMatchMediaLocale
        expect(instance).to.be.a(ValorantEsportsOpenApiSpecification.GetEventDetailsDataEventMatchMediaLocale);
      });

      it('should have the property locale (base name: "locale")', function() {
        // TODO: update the code to test the property locale
        expect(instance).to.have.property('locale');
        // expect(instance.locale).to.be(expectedValueLiteral);
      });

      it('should have the property englishName (base name: "englishName")', function() {
        // TODO: update the code to test the property englishName
        expect(instance).to.have.property('englishName');
        // expect(instance.englishName).to.be(expectedValueLiteral);
      });

      it('should have the property translatedName (base name: "translatedName")', function() {
        // TODO: update the code to test the property translatedName
        expect(instance).to.have.property('translatedName');
        // expect(instance.translatedName).to.be(expectedValueLiteral);
      });

    });
  });

}));
